import { FlowStep } from '@/domain/types';

export const pkceSteps: FlowStep[] = [
  {
    id: 'pkce-1',
    title: 'User Initiates Login',
    description: 'The user clicks the "Login" button in the client application.',
    actorFrom: 'user',
    actorTo: 'client',
    vulnerabilities: [],
    rfcRef: 'RFC 7636 §3',
  },
  {
    id: 'pkce-2',
    title: 'Generate code_verifier',
    description: 'The client application generates a cryptographically random string called code_verifier (43-128 characters from base64url alphabet).',
    actorFrom: 'client',
    actorTo: 'client',
    internalAction: {
      description: 'Client generates a high-entropy random string (code_verifier)',
      actor: 'client',
    },
    vulnerabilities: ['code-verifier-guessable'],
    rfcRef: 'RFC 7636 §4.1',
    securityNote: 'The code_verifier must be unpredictable and have high entropy (min 43 chars from [A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~").',
  },
  {
    id: 'pkce-3',
    title: 'Generate code_challenge',
    description: 'The client creates a code_challenge by hashing the code_verifier with SHA-256 and base64url-encoding the result.',
    actorFrom: 'client',
    actorTo: 'client',
    internalAction: {
      description: 'code_challenge = BASE64URL(SHA256(code_verifier))',
      actor: 'client',
    },
    vulnerabilities: ['plain-code-challenge-method'],
    rfcRef: 'RFC 7636 §4.2',
    securityNote: 'Method MUST be S256 (SHA-256). Plain method provides no protection against code interception.',
  },
  {
    id: 'pkce-4',
    title: 'Redirect with code_challenge',
    description: 'The client redirects the user to the authorization server including the code_challenge and code_challenge_method in the authorization request.',
    actorFrom: 'client',
    actorTo: 'authServer',
    request: {
      method: 'GET',
      endpoint: '/authorize',
      description: 'Authorization request with PKCE parameters',
      params: [
        { name: 'response_type', value: 'code', description: 'Request an authorization code', required: true, example: true },
        { name: 'client_id', value: 'my-spa-app', description: 'The client identifier', required: true, example: true },
        { name: 'redirect_uri', value: 'https://my-spa.com/callback', description: 'Callback URI registered with the authorization server', required: true, example: true },
        { name: 'scope', value: 'openid profile', description: 'Requested scopes', required: false, example: true },
        { name: 'state', value: 'randomState123', description: 'CSRF protection state parameter', required: true, example: true },
        { name: 'code_challenge', value: 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM', description: 'Base64URL(SHA256(code_verifier))', required: true, example: true },
        { name: 'code_challenge_method', value: 'S256', description: 'Hashing method for code_challenge (must be S256)', required: true, example: true },
      ],
    },
    vulnerabilities: ['dns-spoofing', 'open-redirect'],
    rfcRef: 'RFC 7636 §4.3',
  },
  {
    id: 'pkce-5',
    title: 'User Authenticates',
    description: 'The user authenticates with the authorization server (credentials, SSO, etc.).',
    actorFrom: 'user',
    actorTo: 'authServer',
    internalAction: {
      description: 'Auth server validates user credentials',
      actor: 'authServer',
    },
    vulnerabilities: [],
    rfcRef: 'RFC 6749 §4.1.1',
  },
  {
    id: 'pkce-6',
    title: 'Consent Screen',
    description: 'The authorization server displays a consent screen showing what data the client app is requesting.',
    actorFrom: 'authServer',
    actorTo: 'user',
    vulnerabilities: ['iframe-clickjacking'],
    rfcRef: 'RFC 6749 §4.1.1',
    securityNote: 'Auth pages must set X-Frame-Options: DENY to prevent clickjacking.',
  },
  {
    id: 'pkce-7',
    title: 'Authorization Code in Redirect',
    description: 'The authorization server redirects back to the client with the authorization code. The code_challenge is stored by the auth server for later verification.',
    actorFrom: 'authServer',
    actorTo: 'browser',
    request: {
      method: 'GET',
      endpoint: '/callback',
      description: 'Redirect with authorization code',
      params: [
        { name: 'code', value: '夫伊JLDNCySkRdFZjIKOBgY7w', description: 'Short-lived, single-use authorization code', required: true, example: true },
        { name: 'state', value: 'randomState123', description: 'State parameter for CSRF protection', required: true, example: true },
      ],
    },
    vulnerabilities: ['code-interception', 'dns-spoofing'],
    rfcRef: 'RFC 6749 §4.1.2',
    securityNote: 'Even if the code is intercepted, it cannot be exchanged without the code_verifier. PKCE protects against this.',
  },
  {
    id: 'pkce-8',
    title: 'Exchange Code + code_verifier',
    description: 'The client sends the authorization code along with the original code_verifier to the token endpoint. The auth server re-hashes the verifier and compares with stored code_challenge.',
    actorFrom: 'client',
    actorTo: 'authServer',
    request: {
      method: 'POST',
      endpoint: '/token',
      description: 'Token request with PKCE verifier',
      params: [
        { name: 'grant_type', value: 'authorization_code', description: 'Grant type', required: true, example: true },
        { name: 'code', value: '夫伊JLDNCySkRdFZjIKOBgY7w', description: 'Authorization code received earlier', required: true, example: true },
        { name: 'redirect_uri', value: 'https://my-spa.com/callback', description: 'Must match original request', required: true, example: true },
        { name: 'client_id', value: 'my-spa-app', description: 'Client identifier', required: true, example: true },
        { name: 'code_verifier', value: 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk', description: 'The original random string (43-128 chars)', required: true, example: true },
      ],
    },
    vulnerabilities: [],
    rfcRef: 'RFC 7636 §4.5',
    securityNote: 'The auth server verifies that SHA256(code_verifier) matches the stored code_challenge. This proves the client that initiated the flow is the same one exchanging the code.',
  },
  {
    id: 'pkce-9',
    title: 'Token Response',
    description: 'The authorization server validates the code and code_verifier, then issues tokens.',
    actorFrom: 'authServer',
    actorTo: 'client',
    response: {
      status: 200,
      statusText: 'OK',
      description: 'Token response',
      body: {
        access_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1dGguc2VydmVyLmNvbSIsImF1ZCI6WyJodHRwczovL3Jlc291cmNlLnNlcnZlci5jb20iXSwiZXhwIjoxNjA5MjQwMDAwLCJzdWIiOiJ1c2VyMTIzIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSJ9.SignatureHere',
        token_type: 'Bearer',
        expires_in: '3600',
        id_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1dGguc2VydmVyLmNvbSIsInN1YiI6InVzZXIxMjMiLCJub25jZSI6Im5vbmNlLTQzNjgtMTMzNyIsImF1ZCI6Im15LXNwYS1hcHAiLCJleHAiOjE2MDk0MjM2MDAsImlhdCI6MTYwOTQxOTk2MH0.SignatureHere',
      },
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'no-store',
      },
    },
    vulnerabilities: [],
    rfcRef: 'RFC 6749 §5.1',
  },
  {
    id: 'pkce-10',
    title: 'Call Resource Server',
    description: 'The client uses the access_token to call the resource server API.',
    actorFrom: 'client',
    actorTo: 'resourceServer',
    request: {
      method: 'GET',
      endpoint: '/api/user/profile',
      description: 'API request with Bearer token',
      params: [],
      headers: {
        Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...',
      },
    },
    vulnerabilities: ['token-leakage-via-referrer'],
    rfcRef: 'RFC 6749 §2.3',
  },
  {
    id: 'pkce-11',
    title: 'Protected Resource Response',
    description: 'The resource server validates the token and returns the protected resource.',
    actorFrom: 'resourceServer',
    actorTo: 'client',
    response: {
      status: 200,
      statusText: 'OK',
      description: 'Protected resource data',
      body: {
        id: 'user-123',
        name: 'Jane Smith',
        email: 'jane@example.com',
      },
      headers: {
        'Content-Type': 'application/json',
      },
    },
    vulnerabilities: [],
    rfcRef: 'RFC 6749 §2.3',
  },
  {
    id: 'pkce-12',
    title: 'Flow Complete',
    description: 'The client has successfully authenticated the user and obtained an access_token. PKCE has protected the flow against authorization code interception throughout.',
    actorFrom: 'authServer',
    actorTo: 'client',
    internalAction: {
      description: 'PKCE protection verified — code could not have been exchanged by an attacker',
      actor: 'client',
    },
    vulnerabilities: [],
    rfcRef: 'RFC 7636 §6',
    securityNote: 'PKCE closes the attack vector where an intercepted authorization code cannot be exchanged without the original code_verifier.',
  },
];