import { FlowStep } from '@/domain/types';

export const authorizationCodeSteps: FlowStep[] = [
  {
    id: 'authcode-1',
    title: 'User Initiates Login',
    description: 'The user clicks the "Login" button in the client application.',
    actorFrom: 'user',
    actorTo: 'client',
    internalAction: {
      description: 'Client prepares the authorization request URL',
      actor: 'client',
    },
    vulnerabilities: [],
    rfcRef: 'RFC 6749 §4.1.1',
  },
  {
    id: 'authcode-2',
    title: 'Redirect to Authorization Server',
    description: 'The client redirects the user\'s browser to the authorization server with the authorization request.',
    actorFrom: 'client',
    actorTo: 'authServer',
    request: {
      method: 'GET',
      endpoint: '/authorize',
      description: 'Authorization request to the authorization server',
      params: [
        { name: 'response_type', value: 'code', description: 'Indicates that the authorization server should return an authorization code', required: true, example: true },
        { name: 'client_id', value: 'my-web-app', description: 'The client identifier registered with the authorization server', required: true, example: true },
        { name: 'redirect_uri', value: 'https://my-app.com/callback', description: 'The URI the authorization server will redirect to after authorization', required: true, example: true },
        { name: 'scope', value: 'openid profile email', description: 'The scopes the client is requesting access to', required: false, example: true },
        { name: 'state', value: 'xyzABC123', description: 'A random string to prevent CSRF attacks', required: true, example: true },
      ],
    },
    vulnerabilities: ['open-redirect', 'state-omission', 'dns-spoofing'],
    rfcRef: 'RFC 6749 §4.1.1',
    securityNote: 'Without proper redirect_uri validation and state parameter, this step is vulnerable to intercept attacks.',
  },
  {
    id: 'authcode-3',
    title: 'User Authenticates',
    description: 'The user enters credentials on the authorization server\'s login page.',
    actorFrom: 'user',
    actorTo: 'authServer',
    internalAction: {
      description: 'Auth server validates user credentials',
      actor: 'authServer',
    },
    vulnerabilities: [],
    rfcRef: 'RFC 6749 §4.1.1',
  },
  {
    id: 'authcode-4',
    title: 'Consent Screen',
    description: 'The authorization server displays a consent screen showing what data the client app is requesting access to.',
    actorFrom: 'authServer',
    actorTo: 'user',
    vulnerabilities: ['iframe-clickjacking'],
    rfcRef: 'RFC 6749 §4.1.1',
    securityNote: 'If the auth page can be embedded in an iframe, it becomes vulnerable to clickjacking attacks.',
  },
  {
    id: 'authcode-5',
    title: 'Authorization Code in Redirect',
    description: 'After consent, the authorization server redirects the user back to the client\'s redirect_uri with the authorization code in the URL query string.',
    actorFrom: 'authServer',
    actorTo: 'browser',
    request: {
      method: 'GET',
      endpoint: '/callback',
      description: 'Redirect to client with authorization code',
      params: [
        { name: 'code', value: 'SplxlOBeZQQYbYS6WxSbIA', description: 'The authorization code (short-lived, single-use)', required: true, example: true },
        { name: 'state', value: 'xyzABC123', description: 'The state value from the original request (must match)', required: true, example: true },
      ],
    },
    vulnerabilities: ['code-interception', 'token-leakage-via-referrer', 'dns-spoofing'],
    rfcRef: 'RFC 6749 §4.1.2',
    securityNote: 'Authorization codes in URLs are visible in browser history and server logs. This is a known limitation of the basic Auth Code flow.',
  },
  {
    id: 'authcode-6',
    title: 'Exchange Code for Tokens',
    description: 'The client application sends the authorization code to the token endpoint to exchange it for access and refresh tokens.',
    actorFrom: 'client',
    actorTo: 'authServer',
    request: {
      method: 'POST',
      endpoint: '/token',
      description: 'Token request with authorization code',
      params: [
        { name: 'grant_type', value: 'authorization_code', description: 'The type of grant being used', required: true, example: true },
        { name: 'code', value: 'SplxlOBeZQQYbYS6WxSbIA', description: 'The authorization code received in the previous step', required: true, example: true },
        { name: 'redirect_uri', value: 'https://my-app.com/callback', description: 'Must match the redirect_uri from the authorization request', required: true, example: true },
        { name: 'client_id', value: 'my-web-app', description: 'The client identifier', required: true, example: true },
      ],
    },
    vulnerabilities: ['redirect-uri-mismatch', 'dns-spoofing'],
    rfcRef: 'RFC 6749 §4.1.3',
  },
  {
    id: 'authcode-7',
    title: 'Token Response',
    description: 'The authorization server validates the code and returns access_token, refresh_token, and id_token.',
    actorFrom: 'authServer',
    actorTo: 'client',
    request: {
      method: 'POST',
      endpoint: '/token',
      description: 'Token response',
      params: [],
    },
    response: {
      status: 200,
      statusText: 'OK',
      description: 'JSON token response',
      body: {
        access_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1dGguc2VydmVyLmNvbSIsImF1ZCI6WyJodHRwczovL3Jlc291cmNlLnNlcnZlci5jb20iXSwiZXhwIjoxNjA5MjQwMDAwLCJzdWIiOiJ1c2VyMTIzIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.SignatureHere',
        token_type: 'Bearer',
        expires_in: '3600',
        refresh_token: 'tGhz3kXjR8T4sV7qR2mN6cD9yB1fA0eJ',
        id_token: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2F1dGguc2VydmVyLmNvbSIsInN1YiI6InVzZXIxMjMiLCJub25jZSI6Im5vbmNlLTQzNjgtMTMzNyIsImF1ZCI6Im15LXdlYi1hcHAiLCJleHAiOjE2MDk0MjM2MDAsImlhdCI6MTYwOTQxOTk2MH0.SignatureHere',
      },
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'no-store',
      },
    },
    vulnerabilities: [],
    rfcRef: 'RFC 6749 §5.1',
  },
  {
    id: 'authcode-8',
    title: 'Call Resource Server',
    description: 'The client uses the access_token to make an authenticated request to the resource server.',
    actorFrom: 'client',
    actorTo: 'resourceServer',
    request: {
      method: 'GET',
      endpoint: '/api/user/profile',
      description: 'Request to protected resource',
      params: [],
      headers: {
        Authorization: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...',
      },
    },
    vulnerabilities: ['token-leakage-via-referrer', 'token-in-query-string'],
    rfcRef: 'RFC 6749 §2.3',
    securityNote: 'Access tokens should be sent in the Authorization header, not as query parameters.',
  },
  {
    id: 'authcode-9',
    title: 'Protected Resource Response',
    description: 'The resource server validates the access_token and returns the protected resource data.',
    actorFrom: 'resourceServer',
    actorTo: 'client',
    response: {
      status: 200,
      statusText: 'OK',
      description: 'Protected resource data',
      body: {
        id: 'user-123',
        name: 'John Doe',
        email: 'john@example.com',
        picture: 'https://example.com/avatar.jpg',
      },
      headers: {
        'Content-Type': 'application/json',
      },
    },
    vulnerabilities: [],
    rfcRef: 'RFC 6749 §2.3',
  },
];